package com.ruse.donation.daily;

public enum DealType {
    SPEND_25,
    SPEND_50,
    SPEND_100,
    GET_25_PERCENT_BONDS,
    HALF_COST_COSMETIC_TICKETS,
    BUY_2_GET_1_FREE_BOXES,
    OWNER_GOODIEBAG,
    DOUBLE_MEMBERSHIP_PURCHASE,
    PURCHASE_GET_SAME_BOX_FREE,
    DOUBLE_DONATIONS,

    BUY_OWNER_GB_U_GET_1_FREE,
    DONATE_100_GET_2_FREE_ELE_CACHE,
    GET_30_PERCENT_BONDS,
    BUY_1_ELE_CACHE_U_GET_1_FREE,
    SPENT_50_GET_EXTRA_DONO_ISLAND_PULL,
    BUY_T3_MEM_GET_FREE_VOID_CRATE

}
